version: '3.8'

services:
  postgres:
    container_name: measure-gemini-db
    image: postgres
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${PGPORT}

  api:
    container_name: measure-gemini-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - postgres
    environment:
      NODE_ENV: dev
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DATABASE_URL: ${DATABASE_URL}
