version: '3.8'

services:
  postgres:
    container_name: measure-gemini-node
    image: postgres
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apisolid
      PGPORT: 5434
